### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Sascha-T** [kukiteam/kukicraftlauncher#1]
Crashes after it finishes up all the things required to run Minecraft.

**Comment by Sascha-T** [comment]
There is no error in console

**Comment by Sascha-T** [comment]
Becomes zombie process after crash

**Comment by NobodyMiner** [comment]
Can't reproduce or help without error message

**Comment by Sascha-T** [comment]
there is none. maybe add some debugging?
 @NobodyMiner

**Comment by NobodyMiner** [comment]
What exactly should I debug? I can't reproduce this so you need to provide anything that I can use to fix this.

**Comment by Sascha-T** [comment]
Add some console.log()'s maybe?

**Comment by NobodyMiner** [comment]
If there are no errors in the NodeJS console or the Window console I can't do anything about this... Is your java executable available in `PATH`?

**Comment by Sascha-T** [comment]
Yes.

**Comment by Sascha-T** [comment]
![grafik](https://user-images.githubusercontent.com/16324266/47229177-6cac8b80-d3c7-11e8-9802-bf51b2f50cef.png)

**Comment by NobodyMiner** [comment]
Try running the Minecraft client.jar manually. If that works the problem is definitely at the launcher.

**Comment by Sascha-T** [comment]
1.12.2.jar?

**Comment by Sascha-T** [comment]
And send a launch command as you CAN'T run minecraft jars directly afaik

**Comment by NobodyMiner** [comment]
I will add some logging to the next version, soon™

**Comment by Sascha-T** [comment]
[Electron] Ôä╣ Info    Electron ready
[Electron] Ôä╣ Info    Checking Backgrounds
[Electron] Ôä╣ Info    Done checking. Downloading
[Electron] Ôä╣ Info    Found matching files:
[Electron] Ô×£ Trace   BG0.webm
[Electron] Ô£ô Success File found
[Electron] Ô×£ Trace   BG1.webm
[Electron] Ô£ô Success File found
[Electron] Ôä╣ Info    Checking default config
[Electron] Ôä╣ Info    Starting Main Window
[Launcher] Ôä╣ Info    Trying to find Lastlogin info in config
[Launcher] Ô£ô Success Lastlogin found
[Launcher] Ôä╣ Info    Filling text fields with lastlogin info
[Launcher] Ôä╣ Info    Installing Modpack Config
[Launcher] Ôä╣ Info    Downloading Modpack manifest
[Launcher] Ôä╣ Info    Found 20 valid mods
[Launcher] Ôä╣ Info    Loaded 2 Backgrounds to playlist
[Launcher] Ô£ô Success Loading Background [0]
[Launcher] Ôä╣ Info    Launching Game
[Launcher] Ôä╣ Info    Launching game
[Launcher] Ô£ô Success Authentication Successful
[Launcher] Ôä╣ Info    Updating Lastlogin information
[Launcher] Ôä╣ Info    Checking Installation
[Launcher] Ô£ô Success Finished step 'Installing Libraries'
[Launcher] Ô£ô Success Finished step 'Installing Forge Libraries'
[Launcher] Ô£ô Success Finished step 'Installing Assets'
[Launcher] Ôä╣ Info    Checking Mods
[Launcher] Ô£ô Success Finished step 'Installing Mods'
[Launcher] Ôä╣ Info    Launching with additional Arguments:
[Launcher] Ô×£ Trace   -Xmx4G
[Launcher] Ô×£ Trace   -Xms4G
[Launcher] Ôä╣ Info    Launcher will not reopen after closing the game

**Comment by Sascha-T** [comment]
It seems to start Minecraft. Mind leaving the launcher open with a LOG window

**Comment by Sascha-T** [comment]
Zombie process still thing

**Comment by Sascha-T** [comment]
When enabling reopen after closing game it works perfectly fine...

**Comment by Sascha-T** [comment]
I think you have a case of closing the parent process and crashing the child process with that
